apiVersion: apps/v1
kind: Deployment
metadata:
    name: kubectl-telegram-assist-main
    namespace: kube-telegram-assist
    labels:
        app: kubectl-telegram-assist-main
    annotations:
        deployment.kubernetes.io/revision: "6"
        kubectl.kubernetes.io/restartedAt: 2025-02-20T23:28:03.361Z
spec:
    replicas: 1
    revisionHistoryLimit: 3
    selector:
        matchLabels:
            app: kubectl-telegram-assist-main
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
    template:
        metadata:
            labels:
                app: kubectl-telegram-assist-main
                name: kubectl-telegram-assist-main
        spec:
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                  - key: node-role.kubernetes.io/cloud-container-g2
                                    operator: In
                                    values:
                                        - "true"
            containers:
                - name: kubectl-telegram-assist-main
                  image: reg.bea.sh/behnambagheri/kubectl-telegram-assist:main
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
                        name: http
                        protocol: TCP
                  resources:
                      limits:
                          cpu: 100m
                          ephemeral-storage: 100M
                          memory: 200M
                      requests:
                          cpu: 100m
                          ephemeral-storage: 100M
                          memory: 200M
                  envFrom:
                      - configMapRef:
                            name: kubectl-telegram-assist-main-config
                      - secretRef:
                            name: kubectl-telegram-assist-main-secrets
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
            imagePullSecrets:
                - name: docker-reg-3qr1utfn
            restartPolicy: Always
            dnsPolicy: ClusterFirst
            tolerations:
                - key: role
                  operator: Equal
                  value: cloud-container-g2
                  effect: NoSchedule
